<?php

use Illuminate\Database\Seeder;

class SupplierInfo extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */

    protected $suppliers =
                        [
                          ["244 AUTO GLASS & ALUMINUM",""  ],
                          ["310 F. Lara St., Tibag, Baliuag, Bulacan",""  ],
                          ["36 MONTHS IT SOLUTIONS",""  ],
                          ["3J's HARDWARE",""  ],
                          ["4 A's AUTO REPAIR & PARTS","58 Arthur St., W.B.B., Olongapo City"  ],
                          ["4 WHEEL AUTO SUPPLY",""  ],
                          ["4A's AUTO REPAIR & SERVICES",""  ],
                          ["515CT CAR CARE CENTER",""  ],
                          ["515CT CAR CARE CENTER",""  ],
                          ["7-ELEVEN",""  ],
                          ["868 NEW MABUHAY TRADE & BUSINESS INC.",""  ],
                          ["A & Z CAF�",""  ],
                          ["A.J. & A.L. LAPTOP GADGETS TRADING",""  ],
                          ["A.L.D. REFRIGERATION AIR CONDITIONING SERVICE",""  ],
                          ["A.P. LIM ENTERPRISE",""  ],
                          ["A-1 AGRO FERTILIZERS & CHEMICAL SUPPLY","Maharlika Highway, Poblacion, Talavera, Nueva Ecija"  ],
                          ["AARON'S PRINTING PRESS",""  ],
                          ["AB DIZON ENTERPRISES","13 Arthur St., W.B.B., Olongapo City"  ],
                          ["ABJAR COLLECTION'S","133 Salvador St., Baesa, Caloocan City"  ],
                          ["ACE EMPIRE TRADING","8-25th E.B.B., Olongapo City"  ],
                          ["ACE HARDWARE",""  ],
                          ["ACS CYCLE PARTS",""  ],
                          ["ACTION LABS IT SERVICES",""  ],
                          ["ADVENT INDUSTRIAL MACHENERIES, PARTS & SERVICES",""  ],
                          ["AELS ELECTRONICS REPAIR SHOP",""  ],
                          ["AGI'S LAUNDRY SERVICES",""  ],
                          ["AGUA BIYAYA WATER REFILLING STATION","25 Kessing St., New asinan, Olongapo City"  ],
                          ["AIDA'S SANTOS RAMIREZ TRADING","4-23rd St., E.B.B., Olongapo City"  ],
                          ["AIM HIGH SECURITY & WATCHMAN AGENCY",""  ],
                          ["AKINTO MARKETING CORP.","156 A Juan St., Salapan, San Juan City"  ],
                          ["AKY TRADING & GEN. MDSE",""  ],
                          ["ALDICONS TRADING INC.",""  ],
                          ["ALDRICH INDUSTRIAL REPAIR",""  ],
                          ["ALDRICH INDUSTRIAL REPAIR & SERVICE",""  ],
                          ["ALDRIN MEDIC MARKETING SERVICES","Golden City Imus Cavite"  ],
                          ["ALEN VINCI ELECTRONICS & TRADING CENTER",""  ],
                          ["ALICE VARIETY & FROZEN PRODUCT",""  ],
                          ["ALL RECOGNITION GIFT-DAU BRANCH",""  ],
                          ["ALL-IN-GEN. MDSE. ",""  ],
                          ["ALMCO CAR CARE SERVICE CENTRE",""  ],
                          ["ALPHAMED PHARMA","Brgy. N.S. Amoranto, Quezon City"  ],
                          ["AMASAN LETTER PRESS & OFFSET PRINTING","#4-23rd St., E.B.B., Olongapo City"  ],
                          ["AMBEN AUTO ELEC. & CAR AIRCON SHOP",""  ],
                          ["ANALYTE TRADING",""  ],
                          ["ANGEL MUSIC AND SPORTS CENTER","Quiapo, Manila"  ],
                          ["ANGEL TOUCHE'S INKS & PRINTS",""  ],
                          ["ANGEL TOY HOUSE",""  ],
                          ["ANGELES HONRADE STORE",""  ],
                          ["ANGEL'S BURGER",""  ],
                          ["ANNE RAQUEL'S HILLSIDE RESORT, INC.",""  ],
                          ["ANNROB TRADING",""  ],
                          ["ANTHONY PASIA DRY GOODS","JL Gordon Market, Gordon Ave., Pag-asa, Olongapo City"  ],
                          ["APR GENERAL MERCHANDISE","34 Fontaine St., E.B.B., Olongapo City"  ],
                          ["AQUAPIK PURIFIED WATER REFILLING STATION","47-14th St., East Tapinac, Olongapo City"  ],
                          ["ARISTOCRAT RESTAURANT",""  ],
                          ["ARISTOCRAT SUBIC HOMES FOOD, INC.",""  ],
                          ["ARJ FOOD CORP.(RED RIBBON)",""  ],
                          ["ARJ FOOD CORPORATION",""  ],
                          ["ARLENE'S INN",""  ],
                          ["ARLENE'S INN 3",""  ],
                          ["ARMAK RADIATOR REPAIR SHOP","5-26th St., E.B.B., Olongapo City"  ],
                          ["ARMALEEN CELLPHONE & ACCESSORIES TRADING",""  ],
                          ["ARMAN'S MUSICAL INSTRUMENT REPAIR SHOP",""  ],
                          ["ART SPEED PRINT GRAPHICS",""  ],
                          ["ASAYSI TRADING","82 Banaba St., Bo. Barretto, Olongapo City"  ],
                          ["ATAW MARKETING",""  ],
                          ["ATAW MARKETING",""  ],
                          ["AUDIO FREQUENCY LIGHTS & SOUNDS",""  ],
                          ["AUREN CRYSTAL RICE DEALER",""  ],
                          ["AUS TRADING",""  ],
                          ["AUSTIN WATER REFILLING STATION",""  ],
                          ["AZE T-SHIRT PRINTING",""  ],
                          ["B & K TRADING","Rizal St., San Nicolas, Angeles City"  ],
                          ["BABIERA & INFORNON GEN. MDSE ",""  ],
                          ["BABY ANGEL'S CANTEEN",""  ],
                          ["BABYLYN'S GENERAL MERCHANDISE",""  ],
                          ["BACON MARKETING","2714 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["BAGUMBAYAN VOLUNTEERS OF OLONGAPO CITY, INC.",""  ],
                          ["BALANGA-OLONGAPO TRANSPORT SERVICE COOP",""  ],
                          ["BALUYOT FLOWER SHOP","20-22ND St., W.B.B., Olongapo City"  ],
                          ["BAXLEY TAILOR SHOP",""  ],
                          ["BAY CALIBRATION & DIESEL SERVICE SHOP","2765 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["BAY PRESS (SUBIC) CORP.",""  ],
                          ["BAYFRESH REFILLING STATION",""  ],
                          ["BAYFRONT HOTEL",""  ],
                          ["BCM PEST MANAGEMENT SYSTEMS",""  ],
                          ["BCR TRUCKING","Olongapo City"  ],
                          ["BEA'S KITCHEN",""  ],
                          ["BENGDEG RENT A CAR",""  ],
                          ["BENIEL'S VARIETY STORE","40 22nd St., W.B.B., Olongapo City"  ],
                          ["BENJIE'S MUSIC HAUS","4107 R. Magsaysay Blvd.  Sta. Mesa, Manila"  ],
                          ["BEN'S OK CAR ACCESSORIES & PARTS CENTER","391 Banawe St., Sto Domingo, Quezon City"  ],
                          ["BERNIE'S MUFFLER WELDING SHOP",""  ],
                          ["BERTZ CAR WASH",""  ],
                          ["BIOCARE HEALTH RESOURCES","64 Quezon Ave., Quezon City"  ],
                          ["BIOMAXX RESOURCES, INC.","8837 Sampaloc Ave., San Antonio Village, Makati City"  ],
                          ["BIYAYA CANTEEN & CATERING SERVICES",""  ],
                          ["BJ ROOF CENTER & METAL FABRICATION","National Hi-way, Calapacuan Subic, Zambales"  ],
                          ["BLACKBEARD SEAFOOD ISLAND RESTAURANT",""  ],
                          ["BLADE ASIA, INC.",""  ],
                          ["BLUE CRYSTAL WATER REFILLING STATION",""  ],
                          ["BLUE ROCK CORPORATION",""  ],
                          ["BON'S RESTAURANT",""  ],
                          ["BREAD SMILE BAKESHOP",""  ],
                          ["BRENTWOOD APARTELLE",""  ],
                          ["BRITTON DISTRIBUTIONS, INC.","Unit 17B Strata 2000 Bldg. F. Ortigas Jr. Rd. Ortigas Center, Pasig City"  ],
                          ["BRIXMED PHARMACEUTICALS","Sto. Tomas, City of San Fernando, Pampanga"  ],
                          ["BRP PENTAGRAPH ADVERTISING","254 Rizal Ave., East Tapinac, Olongapo City"  ],
                          ["BRYCE ENTERPRISES","Calasiao, Pangasinan"  ],
                          ["BUENAFE PROGRESSIVE RELIABLE EMPLOYMENT & SECURITY SER. AGENCY",""  ],
                          ["BUGHAW GENERAL MERCHANDISE","Project 8, Quezon City"  ],
                          ["BUILDMATE MARKETING","47 A. Pablo St., Karuhatan, Valenzuela City"  ],
                          ["BULGOGI BROTHERS, SUBIC RESTO CORP.",""  ],
                          ["BUMA SUBIC HOTEL",""  ],
                          ["BUMA SUBIC RESTAURANT",""  ],
                          ["BUREAU OF INTERNAL REVENUE",""  ],
                          ["BURGER KING",""  ],
                          ["BVM BIOMEDICAL TRADING",""  ],
                          ["BY THE SEA RESORT RESTAURANT",""  ],
                          ["C&E PUBLISHING, INC.",""  ],
                          ["C.G. CALIBRATION CENTER",""  ],
                          ["C.M. SANTIAGO ADS",""  ],
                          ["C.M. SANTIAGO ADVERTISING","11 Barretto St., E.B.B., Olongapo City"  ],
                          ["CABALEN RESTAURANT",""  ],
                          ["CALOOCAN GAS CORPORATION","4 CBMU Upper Kalaklan, Olongapo City"  ],
                          ["CALOOCAN SALES CENTER INC.",""  ],
                          ["CALTEX SERVICE STATION ",""  ],
                          ["CAMAYAN BEACH RESORT HOTEL",""  ],
                          ["CAMAYAN RESORT",""  ],
                          ["CAPSMAKER INC.","San Fernando, Pampanga"  ],
                          ["CARELINE ENTERPRISES","San Pablo, Laguna City"  ],
                          ["CARESTREAM",""  ],
                          ["CAREWAY ENTERPRISES","Bacoor, Cavite"  ],
                          ["CARLSHEY RTW",""  ],
                          ["CARWOLRD SUBIC, INC.",""  ],
                          ["CASA ENZO AUTOMOTIVE SERVICE CENTER","737 National Rd., San Juan, San Fernando, Pampanga"  ],
                          ["CASANDIG WELDING & MUFFLER SHOP",""  ],
                          ["CATALOGUE SALES & SERVICES, INC.",""  ],
                          ["CATCOR RENT A CAR",""  ],
                          ["CATHAY DRUG, INC.",""  ],
                          ["CATLETTE'S BEADS & CRAFTS SHOP",""  ],
                          ["CB TAMPENGCO CONSTRUCTION & SUPPLY",""  ],
                          ["CCGA REAL ESTATE SERVICES & ADVISORY","Unit 7-C Suntree Tower, Meralco Ave., Brgy. San Antonio, Ortigas Center, Pasig City"  ],
                          ["CCS BIOMEDICAL TRADING","Brgy. San Antonio Bi�an City Laguna"  ],
                          ["CD R KING GEN. MDSE","Harbor Point Mall Branch, SBFZ"  ],
                          ["CD-R KING GENERAL MERCHANDISE",""  ],
                          ["CENTERPNT FOODS CORP/DUNKIN' DONATS",""  ],
                          ["CENTRELLE ENTERPRISES",""  ],
                          ["CENTRO AUTO SUPPLY","22 National Highway, Kalaklan, Olongapo City"  ],
                          ["CES'T LA VIE APARTELLE",""  ],
                          ["CHAIN E BUILDERS","Natianal Hi-way, Bo. Barretto, Olongapo City"  ],
                          ["CHATO'S PHOTO OLONGAPO",""  ],
                          ["CHEDDA GENERAL MERCHANDISE","131 Norton St., New Kalalake, Olongapo City"  ],
                          ["CHEF SAMURAI SUSHI & SAKE",""  ],
                          ["CHEF'S AVE. CANTEEN & CATERING",""  ],
                          ["CHEF'S AVENUE",""  ],
                          ["CHELOUDEN DRUG STORE","87 Rizal Ave., New Banicain, Olongapo City"  ],
                          ["CHESS ARBITERS UNION OF THE PHIL.","Cubao Quezon City"  ],
                          ["CHOAS FOR EVERYTHING SUPERMART",""  ],
                          ["CHOWKING AYALA HARBOR POINT",""  ],
                          ["CHOWKING OLONGAPO RIZAL",""  ],
                          ["CHOWKING SUBIC",""  ],
                          ["CHOWKING-OLONGAPO",""  ],
                          ["CHRIS SPORTS SUBIC INC.","2nd Flr., Harbor Point Mall Rizal Highway, SBFZ"  ],
                          ["CIANNO'S CANTEEN & CATERING SERVICES",""  ],
                          ["CI-CAP GLASS ALUMINUM SUPPLY",""  ],
                          ["CINDY KELLY HOTEL",""  ],
                          ["CIRCLE J GENERAL STORES",""  ],
                          ["CITY GOVERNMENT OF PAMPANGA","1365 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["CITY HOME APPLIANCE & FURNITURE","1365 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["CITY HOMES APPLIANCE & FURNITURES CENTER","1365 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["CJR GRAPHICS AND PRINTING","1455 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["CLAUDIALICIOUS FOOD VENTURES INC.",""  ],
                          ["CLEARVUE PHARMACEUTICAL","Balanga City, Bataan"  ],
                          ["CLOISONNE CHEMICAL PRODUCTS, INC.","66 Stanford ST., Cubao, Quezon City"  ],
                          ["CLOVERHOUSE FURNISING",""  ],
                          ["CLUB MOROCCO",""  ],
                          ["COCOLIME RESTAURANT",""  ],
                          ["COCOLIME RESTAURANT",""  ],
                          ["COFFEE SHOP RESTAURANT",""  ],
                          ["COLORCHECK PAINT ENTERPRISES","2718 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["COLORITE MARKETING",""  ],
                          ["COLORITE MARKETING CORPORATION","1170-8 Pasong Tamo St., Makati City"  ],
                          ["COLORPRINT CLASSIC, INC.","G/F Brickly One Condo, 1372 Cor. Centro St., Espa�a, Sampaloc, Manila"  ],
                          ["COLORVIEW CATV, INC",""  ],
                          ["COMMUTER AUTO SUPPLY",""  ],
                          ["CONCORDE",""  ],
                          ["CONDOTEL ASUNCION",""  ],
                          ["CONSTANCIA CABALAR RICE DEALER",""  ],
                          ["CONSUMMARE  INC.",""  ],
                          ["COPYLINK ENTERPRISES INC.",""  ],
                          ["COPYRITE INC.",""  ],
                          ["CORDS ENTERPRISE",""  ],
                          ["CORK ROOM BISTRO",""  ],
                          ["CORNERSTONE GOODS & GENERAL MERCHANDISE","Baliuag Bulacan"  ],
                          ["CORNERSTONE SPORTING GOOD & GENERAL MERCHANDISE","Bagong Nayon, Baliwag, Bulacan"  ],
                          ["CORONA SUPPLY CO., INC.",""  ],
                          ["CPN DRY GOODS","1981 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["CPT PHOTO CENTER","2067 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["CREA8TIVE PHOTOGRAPHY",""  ],
                          ["CRIS RUBBER STAMP-DRY SEAL",""  ],
                          ["CRISTINA'S FLOWER SHOP",""  ],
                          ["CRUISER MOTOR CYCLE PARTS & SERVICE",""  ],
                          ["CRUISER MOTOR CYCLE PARTS & SERVICE","2596 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["CRUISER MOTOR CYCLE PARTS & SERVICE","2596 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["CTC MOTORCYCLE PART & ACCESSORIES",""  ],
                          ["CTC'S VUNCANIZING SHOP",""  ],
                          ["CTERRY ENTERPRISES","46 Makabayan St.,  Brgy. Obrero, Quezon City"  ],
                          ["CW CARWORLD SUBIC, INC.","Subic Bay Freeport Zone"  ],
                          ["CYBERTECH ROOFING INTERNATIONAL CORP.",""  ],
                          ["D' AMARILLO TAILOR SHOP",""  ],
                          ["D' PESTER'S",""  ],
                          ["D. LIBUNAO GAS MANUFACTURING CORP.",""  ],
                          ["DADDY ED'S RESTAURANT & CONVENIENT STORE",""  ],
                          ["DADS, KAMAYAN, SAISAKI",""  ],
                          ["DAJOBO-ACE TRADING",""  ],
                          ["DAN-BETH GENERAL MERCHANDISE","G/F Globe Bldg., Quezon Blvd., Sta Cruz, Manila"  ],
                          ["DANE DEGALA CASTILLO PHARMACY","Iba Zambales"  ],
                          ["DANG RIC'S CARINDERIA",""  ],
                          ["DANJEN PANSIT MALABON",""  ],
                          ["DARTECH COMMERCIAL & INDUSTRIAL TRADING",""  ],
                          ["DASH GENERAL MERCHANDISE","32 Otero Ave., Mabayuan, Olongapo City"  ],
                          ["DATAWORX OFFICE SOLUTION","16 Mt. Apo, East Tapinac, Olongapo City"  ],
                          ["DATAWORX OFFICE SOLUTIONS CORP.",""  ],
                          ["DAY & NIGHT LAUNDRY",""  ],
                          ["DAY & NIGHT LAUNDRY & DRY CLEANERS",""  ],
                          ["DAYRIT'S KITCHEN & GRILL",""  ],
                          ["DCB TRADING",""  ],
                          ["DDS GENERAL SERVICES ",""  ],
                          ["DE LEON MOBILE",""  ],
                          ["DE PESTER'S PEST MANAGEMENT",""  ],
                          ["DEGA INTERNATIONAL PHARMA","Ayala Alabang Mandaluyong City"  ],
                          ["DEL COMPUTER ENGRAVING SERVICES","2089 C.M. Recto Ave., Quiapo, Manila"  ],
                          ["DEL MONTE LAND TRANSPORT BUS CO., INC.","283 del Monte Ave., Brgy. Manresa, Quezon City"  ],
                          ["DEL ROSARIO MARKETING",""  ],
                          ["DEL ROSARIO MARKETING",""  ],
                          ["DENISE PARES HAUS, ET. AL.",""  ],
                          ["DEPED EMPLOYEES COOPERATIVE",""  ],
                          ["D'FOURTH RENT A CAR",""  ],
                          ["DHEL'S CALIBRATION",""  ],
                          ["DHUSTIN AUTO WORKS","26th St., E.B.B., Olongapo City"  ],
                          ["DIZON ENTERPRISES",""  ],
                          ["DIZON LUMBER, HARDWARE & ELECTRICAL SUPPLY",""  ],
                          ["DJ PARADISE RESORT, INC.",""  ],
                          ["DMC COLUMBUS MARKETING PHILS., INC.","32 Gen. Conception St., Caloocan City"  ],
                          ["DOKIK'S FOOD CORP.",""  ],
                          ["DON GILBERTO P. ROMULO FARMER'S TRAINING CENTER",""  ],
                          ["DPI-DIORELLA PRINTSHOP INT'L CORP.",""  ],
                          ["DREAM OUT LOUD EVENTS & MARKETING","8618 Upper De Guzman Gordon Heights, Olongapo City"  ],
                          ["DUENAS SEPTIC TANK SERVICE",""  ],
                          ["DUE�AS SEPTIC TANK SERVICES",""  ],
                          ["DUNKIN' DONUTS",""  ],
                          ["DURAN MARKETING",""  ],
                          ["DUYAN PENSION HOUSE","Tala Orani, Bataan"  ],
                          ["DXE MARKETING","87, National Highway, Kalaklan, Olongapo City"  ],
                          ["E.C.S. EATERY & FOOD SERVICES","Quezon City"  ],
                          ["E.M. PAULE TRADING",""  ],
                          ["E.R.T. GENERAL MERCHANDISE",""  ],
                          ["E2 & I ENTERPRISES",""  ],
                          ["EASTERN MACHINE WORKS, INC.",""  ],
                          ["EBB TIRE CENTER & SERVICES","2726 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["EC SOLIMAN, JR. CONSTRUCTION &  TRADING",""  ],
                          ["EDMAG CONSTRUCTION SERVICES","28 Corpuz St., West Tapinac, Olongapo City"  ],
                          ["EDWIN & ROSE VARIETY STORE",""  ],
                          ["EFREN MORALES AUTO REPAIR",""  ],
                          ["EJ WEST WING CANTEEN","Sampaguita St., Sta Rita, Olongapo City"  ],
                          ["EL-DO-RA-MI CONSTRUCTION & SERVICES CO.",""  ],
                          ["ELEMENTS DESIGN AND PRINT","Raloos St., Quezon City"  ],
                          ["ELEVEN FOURTEEN MARKETING","5-1st St., East Tapinac, New Asinan, Olongapo City"  ],
                          ["ELIN PHARMACEUTICALS, INC.","Rallos St., Quezon City"  ],
                          ["ELLEN'S LIQUOR'S WINES & GEN. MDSE.",""  ],
                          ["EM & ER CONVENIENCE STORE CORP.",""  ],
                          ["EMARIZ CREATIONS",""  ],
                          ["EMCON GENERAL MERCHANDISE","Lot 34 Blk 3, Mayumi St., Brgy Sta. Rita, Olongapo City"  ],
                          ["EMERALD CANVASS & UPHOLSTERY",""  ],
                          ["EMER'S UPHOLSTERY SUPPLY",""  ],
                          ["EM'S AUTO SUPPLY",""  ],
                          ["EMZWEI TRADING, INC.","5-Rangang St., Brgy. Manresa, Quezon City"  ],
                          ["ENDURE MEDICAL, INC.","San Antonio, Pasig City"  ],
                          ["ENGR. ARNOLD SORIANO",""  ],
                          ["ENIGMA TECHNOLOGIES","1255 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["ERWIN GONZALES GOWNS & BLOSSOM",""  ],
                          ["ESAI HARDWARE","336 Fitration Sta. Rita, Olongapo City"  ],
                          ["ESCALA'S VARIETY STORE",""  ],
                          ["ESCO PHILIPPINES, INC.",""  ],
                          ["ESPADA GRILLS AND AQUA PRODUCTS",""  ],
                          ["ESTER DACIO FASTFOOD",""  ],
                          ["ESTER M. DACIO FAST FOOD",""  ],
                          ["ETERNITY AUTO PARTS","2706 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["EVELYN'S GEN. MDSE.","1750 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["EVERGREEN SEPTIC TANK SERVICES",""  ],
                          ["EVERGREEN SEPTIC TANK SERVICES",""  ],
                          ["EXAL'S RICE & POULTRY","42 Barretto St., E.B.B., Olongapo City"  ],
                          ["EXCELTECH PHILKOR TRADING CORP.",""  ],
                          ["EXPRESSIONS STATIONERY SHOP, INC.",""  ],
                          ["EXSAN ENTERPRISES",""  ],
                          ["EXTREME EXPRESSO CAF�",""  ],
                          ["F & J DE JESUS, INCORPORATED","7636 Guijo cor., Sacred Heart St., San Antonio Village, Makati City"  ],
                          ["F.B. BRAKE CLUTCH",""  ],
                          ["F.B. DE GUZMAN WELDING SHOP","1 Caron St. W.B.B., Olongapo City"  ],
                          ["F7 CREATIVES PRINTRADE SUPPLIES & SERVICES",""  ],
                          ["FABULOUS JEANS & SHIRTS & GEN. MDSE","2043 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["FABULUOS JEANS & SHIRT GEN. MDSE.",""  ],
                          ["FABULUOS JEANS & SHIRTS & GEN. MDSE.",""  ],
                          ["FACUNDO'S JEANS & SHIRTS & GEN. MDSE.",""  ],
                          ["FAJARDO CATERING",""  ],
                          ["FAJARDO'S CANTEEN",""  ],
                          ["FARMACIA MARIA ESPERANZA",""  ],
                          ["FEDDAIRE SALES & GENERAL SERVICES","153 Gordon Ave., Brgy. Kalalake, Olongapo City"  ],
                          ["FEDERAL PEST CONTROL",""  ],
                          ["FERMIDA CONSTRUCTION SERVICES & SUPPLY","Bo. Barretto, Olongapo City"  ],
                          ["FERMIDA GENERAL MERCHANDISE","Mangan-Vaca, Executive Village Subic, Zambales"  ],
                          ["FERMIDA GENERAL MERCHANDISING",""  ],
                          ["FESTIVA DINING CORP.",""  ],
                          ["FG TRADING","3-23rd St., E.B.B., Olongapo City"  ],
                          ["FIESTA 889 HYPER MART",""  ],
                          ["FIRST BUSINESS MACHINE",""  ],
                          ["FIRST SUBIC FOOD VENTURES CORP.",""  ],
                          ["FIVE STAR PHOTOGRAPHY",""  ],
                          ["FLOWER'S ETC., BY ASTRUD",""  ],
                          ["FOODLINK RESOURCE & MANAGEMENT, INC.",""  ],
                          ["FORD SUBIC",""  ],
                          ["FOTON PAMPANGA CORPORATION",""  ],
                          ["FRANCE CY RICE STORE","33 23rd St., W.B.B., Olongapo City"  ],
                          ["FRANCIS MERCHANDISING",""  ],
                          ["FRANCIS REF. & REPAIR SHOP-BRANCH I","33-23rd St., W.B.B., Olongapo City"  ],
                          ["FRANCISCO & CY RICE STORE",""  ],
                          ["FRANCISCO RICE STORE",""  ],
                          ["FRD FOOD & SPICES, INC.",""  ],
                          ["FREEPORT EXCHANGE",""  ],
                          ["FREEPORT MANSION GARDEN HOTEL",""  ],
                          ["FREEPORT OIL",""  ],
                          ["FRONTLAKE INC.",""  ],
                          ["FRONTLAKE, INC.",""  ],
                          ["G.A. LACUNA RICE RETAILER","Para�aque City"  ],
                          ["GAIETY CARMS TRADING",""  ],
                          ["GAIHARZL RADIATOR REPAIR SHOP",""  ],
                          ["GALVAN'S  FOOD CATERING SERVICES ",""  ],
                          ["GAMEVILLE CORPORATION","105 S. Reyes St., Villa Miguela, Pinagbuhatan, Pasig City"  ],
                          ["GAMEWERKZ",""  ],
                          ["GAPENAS FOOD HAUS","1690 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["GARBES-DIZON GOODYEAR AUTO CARE",""  ],
                          ["GARBES-DIZON SERVITEK",""  ],
                          ["GARBES-DIZON SERVITEK",""  ],
                          ["GARBES-DIZON TIRE & SERVICE CENTRE",""  ],
                          ["GC AUTO SUPPLY",""  ],
                          ["GCLT GENERAL MERCHANDIZING",""  ],
                          ["GEAR UP MOTORCYCLE",""  ],
                          ["GENTRIC TRADING",""  ],
                          ["GERRY'S GRILL",""  ],
                          ["GETZ BROS. PHILS., INC.","5/F Ortigas Bldg., Ortigas Ave., Pasig City"  ],
                          ["GIDEONCOMP MERCHANDISING",""  ],
                          ["GIGATRON COMPUTER CENTER","2256 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["GINA'S JOLAND PORTRAIT",""  ],
                          ["GLOBAL HOTEL & LEISURE PROPERTIES, INC.",""  ],
                          ["GLOBAL HOTEL & LEISURE PROPERTIES, INC.",""  ],
                          ["GMA2 PRINTING & SERVICES",""  ],
                          ["GOLDEN DRAGON RESTAURANT","615 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["GOLDEN STATE ALUMINUM GLASS & GEN. MDSE.",""  ],
                          ["GOLDEN TRADE ENTERPRISES",""  ],
                          ["GOLDENCRAFTS ENTERPRISES",""  ],
                          ["GOLDILOCKS BAKESHOP","Ortigas Center, Pasig City"  ],
                          ["GOODFELLOW PHARMA CORP.",""  ],
                          ["GOODYEAR HARDWARE & ELECTRICAL SUPPLY","15 Gordon Ave., Pag-asa, Olongapo City"  ],
                          ["GOURMET GARAGE and DELICATESSEN",""  ],
                          ["GRACEL COMMERCIAL","Paco Manila"  ],
                          ["GRAND MAHLE CORPORATION",""  ],
                          ["GRAND PHOTOGRAPHERS ASSOCIATION-Olongapo City Group Inc.",""  ],
                          ["GRAND SEAS HOTEL","667 G. Puyat St., Brgy. 309 Zone 030, Quiapo, Manila"  ],
                          ["GRANDERS SPORTS CENTER",""  ],
                          ["GRANDERS SPORTS CENTER",""  ],
                          ["GREENSUN AUTOMOTIVE ENTERPRISES, INC. NISSAN BATAAN",""  ],
                          ["GREENWICH",""  ],
                          ["GREGG'S WOODCRAFT","673 Amapola St., Sta Rita, Olongapo City"  ],
                          ["GREGORIO Z. ROBLES",""  ],
                          ["GUERRERO CENTER CYCLE PARTS",""  ],
                          ["GUERRERO CENTER CYCLE PARTS","673 Amapola St., Sta Rita, Olongapo City"  ],
                          ["GV AD VENTURES, INC.",""  ],
                          ["H.J. EXPRESS RENT A CAR",""  ],
                          ["HAIMA CARS PAMPANGA","Jose Abad Santos Ave., CSFP"  ],
                          ["HAPAG KAINAN SA 18th ST. E.B.B.",""  ],
                          ["HAPPY VALLEY SUPERMARKET","64-18th St., E.B.B., Olongapo City"  ],
                          ["HARRIS VARIETY STORE",""  ],
                          ["HBW GENERAL MERCHANDISE","11 Arthur St., W.B.B., Olongapo City"  ],
                          ["HERALDO CABRIDO/MT. PINATUBO MEDIA SURVIVORS",""  ],
                          ["HERMES CARINDERIA",""  ],
                          ["HERMIES DRY GOODS",""  ],
                          ["HIMEX CORPORATION","Ortigas, Pasig City"  ],
                          ["HLURB NORTHERN TAGALOG REGION (NTR)",""  ],
                          ["HOLLYS",""  ],
                          ["HONRADEZ COPY SYSTEM",""  ],
                          ["HONRADEZ COPY SYSTEM","Olongapo City"  ],
                          ["HOTSHOTS BURGER SUBIC CORP.",""  ],
                          ["HOTSHOTS BURGER SUBIC CORP.",""  ],
                          ["HRRP TRADING","809 Ritz Rd., E. Rodriguez Sr. Le Mariche Subd. Kalusugan, Dist IV Quezon City"  ],
                          ["HUBERT ENTERPRISE",""  ],
                          ["IBONROP MARKETING",""  ],
                          ["I-DAS GENERAL MERCHANDISE",""  ],
                          ["ILOCANDIA DROPS REFILLING STATION",""  ],
                          ["INFINITY EVENTS & FLOWER SHOP","18A Brill St., W.B.B., Olongapo City"  ],
                          ["INFOMAX ENTERPRISE-BRANCH III",""  ],
                          ["INK STATION BY BETCHAAZ",""  ],
                          ["INK STATION BY BETCHAAZ",""  ],
                          ["INNOGEN PHARM",""  ],
                          ["INNOVASCEND",""  ],
                          ["INTERGRATED PHARMACEUTICAL INC.",""  ],
                          ["INTERNATIONAL FREEPORT TRADERS, INC.",""  ],
                          ["INTERNATIONAL HEAVY EQUIPMENT CORP.","155 Panay Ave., Quezon City"  ],
                          ["INTERNATIONAL HEAVY EQUIPMENT CORP.","155 Panay Ave. Quezon City"  ],
                          ["INVENEX INCORPORATED",""  ],
                          ["IRAM TRIBAL MULTI-PURPOSE COOPERATIVE","Iram, New cabalan, Olongapo City"  ],
                          ["IRON SIGTHED TACTICAL GEAR SHOP","Manila"  ],
                          ["ISLAND'S FANTASY SOUVENIR & RTW",""  ],
                          ["ISUZU PAMPANGA",""  ],
                          ["IZER GENERAL MERCHANDISE","Cainta, Rizal"  ],
                          ["J.T.C MARKETING",""  ],
                          ["J.T.C. MARKETING",""  ],
                          ["JA DIOCES PALAY BUYING & RICE RETAILING",""  ],
                          ["JACER VULCANIZING SHOP",""  ],
                          ["JAKE'S FOOTWEAR",""  ],
                          ["JAMES BICYCLE & MOTOR PARTS","1515 Rizal Ave., West Tapinac, Olongapo"  ],
                          ["JAMES UY MOTOR REWINDING","9-29th St., E.B.B., Olongapo City"  ],
                          ["JAMJLE EQUIPMENTS & GENERAL MERCHANDISE","Lot 12, Unit K, Commitment St., SBIP Phase I, SBFZ"  ],
                          ["JAMJLE PROPERTIES SUBIC & DEV'T CORP.","SBFZ"  ],
                          ["JANSAM TRADING","103B-Hansen St., East Tapinac, Olongapo City"  ],
                          ["JAPAN HOME, INC.",""  ],
                          ["JASCOLICE TRADING",""  ],
                          ["JASCOLINE TRADING",""  ],
                          ["JASMIN PRESIOUS JADE HOTEL",""  ],
                          ["JASON FRONDA","Purok 5, Old Cabalan, Olongapo City"  ],
                          ["JAT ADS ADVERTISING & SUPPLIES","Stall 5-16 JLGPM&M Pag-asa, Olongapo City"  ],
                          ["JAY AUTO PAINTSHOP",""  ],
                          ["JAY-CZAR PRINTING & BINDING SERVICES","179 Rizal San Nicolas Castillejos, Zambales"  ],
                          ["JBV ADVERTISING","# 1 Harris St., E.B.B., Olongapo City"  ],
                          ["JC FURNITURE & APPLIANCES SALES","1155 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["JC MARKETING","109 Fendler St., East Tapinac, Olongapo City"  ],
                          ["JC VILLANUEVA MACHINE WORKS",""  ],
                          ["JEANELL GENERAL MERCHANDISE",""  ],
                          ["JECT GENERAL MERCHANDISING",""  ],
                          ["JEDDA'S AUTO REPAIR SHOP",""  ],
                          ["JELEEBEE SUPERMART","20-Magsaysay Drive, Olongapo City"  ],
                          ["JELEEBEE VAN SERVICES",""  ],
                          ["JE'S AUTO SUPPLY",""  ],
                          ["JET MASTER ACCESSORIES & PARTS","2596 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["JHAN PAULE'S DINNER & TAKE OUT",""  ],
                          ["JHUN CARS UPHOLSTERY",""  ],
                          ["JHUN ELECTRICAL SHOP",""  ],
                          ["JHUN'S RENT A CAR","Subic Zambales"  ],
                          ["JJ HARDWARE & CYCLE PARTS",""  ],
                          ["JJ LACEBAL CONSTRUCTION",""  ],
                          ["JJ PRINTING PRESS",""  ],
                          ["JJL GLASS & ALUMINUM SUPPLY",""  ],
                          ["JLGMHESC",""  ],
                          ["JM DIGITAL PRODUCTION",""  ],
                          ["JMN ENTERPRISE","12-4th St., West Tapinac, Olongapo City"  ],
                          ["JODEL REPAIR SHOP",""  ],
                          ["JODEL REPAIR SHOP",""  ],
                          ["JODEL'S REAPIR SHOP","2698 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["JODEL'S REPAIR SHOP",""  ],
                          ["JOENIS AUTO SUPPLY",""  ],
                          ["JOEY T. MARANTAN SCHOOL SUPPLIES",""  ],
                          ["JOFOX COMPUTER REPAIR & SERVICES",""  ],
                          ["JOHAN'S ADVENTURE DIVE CENTER",""  ],
                          ["JOHAN'S ROOMS & RESTAURANT",""  ],
                          ["JOHN GRAPHIC IMAGE ADVERTISING",""  ],
                          ["JOJO'S RUBBER STAMP & DRY SEAL",""  ],
                          ["JOLIBEE FOODS CORP.",""  ],
                          ["JOLLIBEE OLONGAPO TRIANGLE",""  ],
                          ["JOLLIBEE OLONGAPO/UP LINE FOODS CORP.",""  ],
                          ["JOLLIBEE SUBIC BAY",""  ],
                          ["JOLLIBEE SUBIC-LOT 21",""  ],
                          ["JOLLIBEE ULO NG APO",""  ],
                          ["JORGE TORRES/TVD ADVERTISING","1 Harris, E.B.B., Olongapo City"  ],
                          ["JOSEFINA'S NEWSPAPER DISTRIBUTOR",""  ],
                          ["JOVEN LANSANG VARIETY STORE",""  ],
                          ["JOYFOODS CORP.",""  ],
                          ["JP&R CONCEPT ENGINEERING & SUPPLY",""  ],
                          ["JRA LIGHTS & SOUNDS",""  ],
                          ["JRJ PHARMA MED. GALLERY & GEN. MDSE.","No. 65 Rizal Ave., New Banicain, Olongapo City"  ],
                          ["JTC MARKETING",""  ],
                          ["JUJACAS PRINTING PRESS",""  ],
                          ["JULIES BAKESHOP",""  ],
                          ["JULIE'S GLASS & ALUMINUM SUPPLY",""  ],
                          ["JUNLING UPHOLSTERY SHOP",""  ],
                          ["JUN'S BALLOONS",""  ],
                          ["JUVILEE DRAPERY & TAILOR SHOP",""  ],
                          ["JV SPRINTER AUTO SUPPLY","12-20th St., E.B.B., Olongapo City"  ],
                          ["JV's PRINTING PRESS","Gatiawin Arayat Pampanga"  ],
                          ["KCF TRADING",""  ],
                          ["KELVIN AIRE AIR CON & REF. SERVICES","Makati City"  ],
                          ["KENDRAKE GENERAL MERCHANDISE","Bagong Silang, Caloocan City"  ],
                          ["KFC SM OLONGAPO",""  ],
                          ["KHENT AIRCONDITION & REFRIGERARION SHOP",""  ],
                          ["KIA PAMPANGA",""  ],
                          ["KIEL MIKO PIZZA HAUS",""  ],
                          ["KIMONO KEN CORP.",""  ],
                          ["KING NJP GENERAL MERCHANDISE","33 18th St. E.B.B., Olongapo City"  ],
                          ["KING'S BAKESHOP BRANCH 1",""  ],
                          ["KITCHEN TOMATO","SBFZ"  ],
                          ["KITZIE'S NATIVE CUISINE RESTAURANT",""  ],
                          ["K-ONE ANGELES SHOPPING CENTER",""  ],
                          ["KONG'S RESTAURANT",""  ],
                          ["KONG'S TAVERN",""  ],
                          ["KOPYERS GEN. MERCHANDISE",""  ],
                          ["KOPYERS GENERAL MERCHANDISE",""  ],
                          ["KOPYRICH COPY CENTER",""  ],
                          ["KSERVICO TRADE INC.,","2701 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["K-SPORTING GOODS & GENERAL MERCHANDISE",""  ],
                          ["KUSINA NI ALING JOSEFINA BASI",""  ],
                          ["L & D MOTORS","66 Gallegher 10th St., East Tapinac, Olongapo City"  ],
                          ["L n G AUTO SUPPLY",""  ],
                          ["L&D Motors",""  ],
                          ["LAFFS BITES & DRINKS, INC.",""  ],
                          ["LALYN'S PRINTSTATION","5 Ragang St., Banawe, Quezon City"  ],
                          ["LAND MANAGEMENT BUREAU",""  ],
                          ["LARRAH PRINTRADE SERVICES & SUPPLIES",""  ],
                          ["LARRAH PRINTRADE SERVICES & SUPPLIES","1779 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["LC LUMBER & HARDWARE",""  ],
                          ["LEXSTAR GRAPHIC ARTS",""  ],
                          ["LIBAY'S HALO-HALO SA GAPO",""  ],
                          ["LIBERTY'S EMBROIDERY & BALLCAPS",""  ],
                          ["LIGHT HOUSE MARINA RESORT",""  ],
                          ["LINMER PHARMA, INC.","Culiat, Tandang Sora, Quezon City"  ],
                          ["LIVESOUNDS! LIGHTS & SOUNDS",""  ],
                          ["LJS PRINTRADE SUPPLIES & SERVICES","103-B Hansen St., East Tapinac, Olongapo City"  ],
                          ["LLACUNA'S KEY SHOP & RUBBER STAMP","2067K-21st St., W.B.B., Olongapo City"  ],
                          ["LLACUNA'S KEY SHOP & RUBBER STAMP",""  ],
                          ["LLACU�A'S KEY SHOP & RUBBER STAMP","San Vicente Apalit Pampanga"  ],
                          ["LOIS LEMBER LOUIE GENERAL MECHANDISE","1014 San Vicente, Apalit Pampanga"  ],
                          ["LOIS LEMBER LOUIE GENERAL MERCHANDISE","1014 San Vicente Apalit, Pampanga"  ],
                          ["LOIS MCLOUIE METALCRAFT",""  ],
                          ["LORIMAR PUBLISHING, INC.","776 Aurora Boulevard Cor., Boston St., Cubao, Quezon City"  ],
                          ["LORWINS GENERAL MERCHANDISE",""  ],
                          ["LOS POLLUELOS LECHON",""  ],
                          ["LUCKY C CYCLE SUPPLY",""  ],
                          ["LUCKY GIA METAL WORKS & RECAP CENTER",""  ],
                          ["LUCKY RJ MOTORCYCLE PARTS & ACCESSORIES","110 Fendler, East Tapinac, Olongapo City"  ],
                          ["LUCKY RJ MOTORCYCLE PARTS & ACCESSORIES","110 Fendler, East Tapinac, Olongapo City"  ],
                          ["LUCKYMATE COLOR GENERAL MERCHANDISE","2450 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["LURING'S BARBEQUE HOUSE CORP.",""  ],
                          ["M & H (SUBIC), INC.",""  ],
                          ["M & M XEROX COPY",""  ],
                          ["M & M XEROZ COPY","31-23rd St., W.B.B., Olongapo City"  ],
                          ["M PANGILINAN VARIETY STORE",""  ],
                          ["M.A.C. PERFORMANCE",""  ],
                          ["M.A.G. INTERNET SHOP",""  ],
                          ["M.A.G. INTERNET SHOP","126-A Malakas St., Diliman, Quezon City"  ],
                          ["M21 GAS INC.",""  ],
                          ["M22 TRADING",""  ],
                          ["MABBIE GENERAL MERCHANDISE",""  ],
                          ["MABUHAY KAIN DITO",""  ],
                          ["MAGGIE'S BALOON",""  ],
                          ["MAIL & MORE BUSINESS SERVICES, INC.",""  ],
                          ["MALEX TRADING","Brgy. 415 Sampaloc, Metro Manila"  ],
                          ["MALLARE'S BICYCLE STORE",""  ],
                          ["MAMA CILA'S SARI-SARI STORE","City of San Fernando, Pampanga"  ],
                          ["MAMOU'S CAF�",""  ],
                          ["MANABAT TRADING CORP.","Mac Arthur Hi-way Dolores San Fernando Pampanga"  ],
                          ["MANANQUIL AUTO SUPPLY",""  ],
                          ["MANBUILT AUTO DEVELOPMENT",""  ],
                          ["MANG INASAL",""  ],
                          ["MANGO VALLEY HOTEL",""  ],
                          ["MANILA MERCHANDISING","67 Elica�o St., E.B.B., Olongapo City"  ],
                          ["MANILA SEEDLING BANK FOUNDATION, INC.",""  ],
                          ["MANSION BAKESHOP",""  ],
                          ["MANSION HARDWARE",""  ],
                          ["MANSION HOTEL",""  ],
                          ["MANSION RESTAURANT",""  ],
                          ["MANUEL ZENAIDA RICE RETAILER",""  ],
                          ["MAPCAR TRADING","38-23rd St., W.B.B., Olongapo City"  ],
                          ["MARCKKI SHIRT SHOP","9 Mabini St., E.B.B., Olongapo City"  ],
                          ["MARIA CECILIA LEGASPI GAYATIN MERCHANDISE",""  ],
                          ["MARIETTA'S MEAT STALL",""  ],
                          ["MARITONI'S FOOD CATERING SERVICES","Lumanbayan, Calapan City Oriental Mindoro"  ],
                          ["MARK ANTHONY LEGASPI ENTERPRISES","1435 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["MARK ANTHONY LEGASPI ENTERPRISES",""  ],
                          ["MARK T. QUIJANO",""  ],
                          ["MARK'S A/C SYSTEM",""  ],
                          ["MARK'S AIRCONDITIONING SYSTEM",""  ],
                          ["MARLYN FLOWER SHOP","23-24th St. W.B.B., Olongapo City"  ],
                          ["MARLYN FLOWERSHOP",""  ],
                          ["MARLYN'S GARMENT","Sta Monica Subd., Subic, Zambales"  ],
                          ["MARS AUTO PARTS SUPPLY",""  ],
                          ["MART ONE",""  ],
                          ["MARTI PRINTER",""  ],
                          ["MARZAN PHARMA CORPORATION","Unit A Inmed Bldg., 1407 Rizal Ave., Brgy. 334 Zone 033 Sta. Cruz, Manila"  ],
                          ["MASTER HARDWARE",""  ],
                          ["MASTER LUMBER",""  ],
                          ["MATIAS PRESS",""  ],
                          ["MAX FLOWERS SHOP","23-24th St. W.B.B., Olongapo City"  ],
                          ["MAX'S RESTAURANT",""  ],
                          ["MC DONALD'S McArthur Maimpis Branch",""  ],
                          ["MC DONALD'S OLONGAPO-RIZAL","MC DONALD's"  ],
                          ["MC DONALD'S OLONGAPO MAGSAYSAY",""  ],
                          ["MC DONALD'S SUBIC BAY GATEWAY RIZAL HIGHWAY",""  ],
                          ["MC RENT A CAR",""  ],
                          ["MCKOI UPHOLSTERY SHOP",""  ],
                          ["MEAT PLUS CAF�",""  ],
                          ["MEDECIA ENTERPRISES",""  ],
                          ["MEDICAL CENTER TRAINING CORP.","City of San Fernando Pampanga"  ],
                          ["MEDICEL ENTERPRISES","8th Ave., Villa Julita SBVD., San Fernando Pampanga"  ],
                          ["MEDICOTEK INC.","Edsa, Mandaluyong City"  ],
                          ["MEDIGREEN PHARMACY","89 Rizal Ave., New Banicain, Olongapo City"  ],
                          ["MEDISAFE PHILIPPINES, INC.","Quezon City"  ],
                          ["MEDISETH ENTERPRISE","1-15th St. Joseph Compound Tabun, Angeles City"  ],
                          ["MEGAMAR MOTORS PHILIPPINES INC.",""  ],
                          ["MEGAMAR MOTORS PHILS. INC.",""  ],
                          ["MEGATSAI","Balubad Porac, Pampanga"  ],
                          ["MEKENI  FOOD CORPORATION","Balubad Porac, Pampanga"  ],
                          ["MEKENI FOOD CORP.",""  ],
                          ["MER-VIL FASTFOOD",""  ],
                          ["METRO DRUG","Taguig, Metro Manila"  ],
                          ["MICHKYLE TRADING","149 Avocado St., Sta Rita, Olongapo City"  ],
                          ["MIGUEL'S FISHING SUPPLY & GENERAL MERCHANDISE","10 National Highway, Calapandayan, Subic"  ],
                          ["MILAGROS SONZA'S TRUCKING SERVICES","3 Rodriguez St., New Kalalake, Olongapo City"  ],
                          ["MILLENIUM TIRE CORPORATION","195 Lower Kalaklan, Olongapo City"  ],
                          ["MILLER'S FURNITURE COLLECTION",""  ],
                          ["MINI KONG'S EXPRESS RESTAURANT",""  ],
                          ["MINI STOP",""  ],
                          ["MM CASTILLO GENERAL MERCHANDISE",""  ],
                          ["MOCA BLENDS",""  ],
                          ["MON-MON TIRE SURPLUS & VULCANIZING SHOP",""  ],
                          ["MONTON ENTERPRISES","129 National Rd.,Lower Kalaklan, Olongapo City"  ],
                          ["MOONBAY MARINA LEISURE RESORT",""  ],
                          ["MOONBAY MARINA RESTAURANT",""  ],
                          ["MOONBAY MARINA VILLAS",""  ],
                          ["MORATA GLASS & ALUMINUM SUPPLY",""  ],
                          ["MOUNTAIN WOODS INN, INC.",""  ],
                          ["MR JOSE YAMSON",""  ],
                          ["MR. FIX IT",""  ],
                          ["MRL CYBERTEC CORPORATION","3/F MRL Tower No.124 Malaks St., Central District Diliman, Quezon City"  ],
                          ["MRY AUTO SUPPLY",""  ],
                          ["MRY AUTO SUPPLY-BRANCH I","22 Upper Kalaklan, Olongapo City"  ],
                          ["MSE SIGN SHOP","Stall 12 Pag-asa Market, Olongapo City"  ],
                          ["MUSTARD SEED SYSTEM CORPORATION","19 Arthur St., W.B.B., Olongapo City"  ],
                          ["MVV INTERNET CAF�",""  ],
                          ["MVV WATER REFILLING STATION",""  ],
                          ["MVV WATER REFILLING STATION","19 Arthur, W.B.B., Olongapo City"  ],
                          ["MVW WATER REFILLING STATION","Harbor Point, SBFZ"  ],
                          ["MY MOMMY'S HOUSE OF KARE-KARE",""  ],
                          ["NATIONAL BOOK STORE",""  ],
                          ["NATIONAL BOOKSTORE SM OLONGAPO",""  ],
                          ["NATIONAL STATISTICS OFFICE",""  ],
                          ["NAUTILUS DIVE & SPORTS CENTER CORP.",""  ],
                          ["NAVAL BAKERY & MERCHANDISING",""  ],
                          ["NEBS FOOD & REFRESHMENT",""  ],
                          ["NEW CHERRY BLOSSOM CATERING SERVICES","12 Ohio St., Upper Kalaklan, Olongapo City"  ],
                          ["NEW CITY GLASS & ALUMINUM",""  ],
                          ["NEW FENG HUANG RESTAURANT",""  ],
                          ["NEW HAPPY VALLEY SUPERSTORE",""  ],
                          ["NEW RAPRAP TRUCKING SERVICES",""  ],
                          ["NEW SHELL MARINA SERVICE STATION","1939 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["NEWCARD ENTERPRISES",""  ],
                          ["NEWSTAR SHOPPING MART INC.","18 Magsaysay Drive, New Asinan, Olongapo City"  ],
                          ["NEXT FRONTIER TRANSPORT SERVICE",""  ],
                          ["NGE HARDWARE & COSTRUCTION SUPPLY","Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["NGE TRADING","595 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["NICCO'S RESTAURANT",""  ],
                          ["NICOLAS MERCHANDISING",""  ],
                          ["NICO'S CAR WASH",""  ],
                          ["NIDAS AUTO SUPPLY","2733 Rizal Ave., W.B.B., Olongapo City"  ],
                          ["NIHONRYORI SAKURA REST.",""  ],
                          ["NIKKA TRADING","#4 23rd St., E.B.B., Olongapo City"  ],
                          ["NIKKI AND MOM'S KITCHEN",""  ],
                          ["NISSAN BATAAN",""  ],
                          ["NISSAN PAMPANGA",""  ],
                          ["NOEL KEY SHOP & RUBBER STAM","Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["NORBIE'S PRINTS AND GRAPIX CENTER","38 R. Magsaysay Drive East Tapinac, Olongapo City"  ],
                          ["NORDSMAIRE HARDWARE","22 Barretto St., E.B.B., Olongapo"  ],
                          ["NORTHVIEW GLASS & ALUMINUM SUPPLY","22 Barretto St., E.B.B., Olongapo"  ],
                          ["NORTHVIEW TRADING",""  ],
                          ["NOVELEAH FASTFOOD",""  ],
                          ["NT GLOBAL INC.",""  ],
                          ["NUHAUS LOGISTICS INC.","15-20th E.B.B., Olongapo City"  ],
                          ["NVA GENERAL MERCHANDISE",""  ],
                          ["O.B.P. TRADING",""  ],
                          ["OCAMPO'S OLONGAPO",""  ],
                          ["OCEAN VIEW BEACH RESORT",""  ],
                          ["OCGEMPC",""  ],
                          ["OFFICE WAREHOUSE INC.",""  ],
                          ["OLDIES BUT GOODIES AND BASIC MODES BAND",""  ],
                          ["OLONGAPO CADD & PLOTTING CENTER",""  ],
                          ["OLONGAPO CADD & PLOTTING CENTER",""  ],
                          ["OLONGAPO CALTEX SERVICE STATION",""  ],
                          ["OLONGAPO CALTEX SERVICE STATION","1599 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["Olongapo City Convention Center",""  ],
                          ["OLONGAPO COMMUTER AUTO SUPPLY  ","2710 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["OLONGAPO EXPRESS",""  ],
                          ["OLONGAPO GAS CORP.",""  ],
                          ["OLONGAPO GAS CORPORATION",""  ],
                          ["OLONGAPO GLOBAL TRAINING CENTER","NO BUSINESS PERMIT"  ],
                          ["Olongapo Line Foods Corp./Jollibee",""  ],
                          ["OLONGAPO LIVELIHOOD SUPPORT SYSTEM",""  ],
                          ["OLONGAPO PIONEER BUSINESS MACHINE",""  ],
                          ["OLONGAPO RICO'S RESTAURANT",""  ],
                          ["OLONGAPO RICO'S RESTAURANT",""  ],
                          ["OLONGAPO TRAVEL LODGE",""  ],
                          ["OLONGAPO WIMPY'S FOOD PLAZA NO. 2",""  ],
                          ["ONE MALL'O POLY WORLD, INC.","Space No. 2062-2063 Harbor Point Mall, SBFZ"  ],
                          ["ORIENT FREIGHT INTERNATIONAL INC.","Makati City"  ],
                          ["OSCSMTSC, INC.",""  ],
                          ["OUR TODAYS WATER ALKALINE PURE & MIN WATER STATION",""  ],
                          ["OWEL AUTO ELECTRICAL & CAR AIRCON SHOP",""  ],
                          ["OWEN'S REFRIGERATION & CAR AIRCON SERVICES",""  ],
                          ["PACLA HYDRAULIC HOUSE","225 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["PAINT PLUS COLOUR'S GEN. MERCHANDISE",""  ],
                          ["PAMPANGA HOSPITAL PRODUCTS","City of San Fernando Pampanga"  ],
                          ["PANCAKE HOUSE, INC.",""  ],
                          ["PANDAYAN BOOKSHOP INC.","32-18th St., E.B.B., Olongapo City"  ],
                          ["PANGILINAN VARIETY STORE",""  ],
                          ["PARADIGM TOP-NOTCH TRADING",""  ],
                          ["PARFON PRINTING SERVICES","1752, Dian St., Palanan Makati City"  ],
                          ["PATIENT CARE CORPORATION","City of San Fernando Pampanga"  ],
                          ["PAULYN'S CATERING",""  ],
                          ["PAULYN'S CATERING",""  ],
                          ["PAYLESS FOOT SPECIALTY RETAILERS, INC.","Harbor Point, SBFZ"  ],
                          ["PC LIVE",""  ],
                          ["PC OK COMPUTERS",""  ],
                          ["PC OK COMPUTERS",""  ],
                          ["PDJ's TRADING",""  ],
                          ["PEDRO CRUZ VARIETY STORE",""  ],
                          ["PENTAGRAPH ADVERTISING",""  ],
                          ["PERLY'S VARIETY STORE",""  ],
                          ["PERT CYCLE PARTS",""  ],
                          ["PESIMO ELECTRICAL PARTS SUPPLY",""  ],
                          ["PHIL-AM MART APPLIANCES, FURNITURE & GASUL DEALER","Quezon City"  ],
                          ["PHIL-AM MART GASUL DEALER",""  ],
                          ["PHIL-AM MART-OUTLET 3","148 Otero Ave., Mabayuan, Olongapo City"  ],
                          ["PHILCOPY CORP.-OLONGAPO BRANCH",""  ],
                          ["PHILCOPY CORPORATION-OLONGAPO BRANCH","3-B 1st New Asinan, Olongapo City"  ],
                          ["PHILECOLOGY SYSTEMS CORPORATION","2nd Fl. RII Bldg. 136 Malakas St., Diliman, Quezon City"  ],
                          ["PHILIPPINE STATISTICS AUTHORITY","Olongapo City"  ],
                          ["PHOTOGENICS DIGITAL PHOTOGRAPHY",""  ],
                          ["PHOTOLINE ENTERPRISES CORP.",""  ],
                          ["PICTURE CITY","SBFZ"  ],
                          ["PMR TRADING","8 Kessing St., New Asinan, Olongapo City"  ],
                          ["POWERBOOKS SPECIALTY STORE",""  ],
                          ["PPCI SUBIC, INC.","SBFZ"  ],
                          ["PRE-ANS ENTERPRISES","Davsan Subd., Sindalan, City of San Fernando Pampanga"  ],
                          ["PRECISION TEK",""  ],
                          ["PRINT IMPRESS SUPPLIES & SERVICES",""  ],
                          ["PRINTON PRESS",""  ],
                          ["PRO WORX ENGINEERING SERVICES",""  ],
                          ["PROFAIR TRADE DEV'T AGENCY SC LTD., CO.",""  ],
                          ["PROGRESSIVE MEDICAL CORPORATION","200 C, Raymundo Ave., Pasig City"  ],
                          ["PROJECT R AUTO SHOP",""  ],
                          ["PSI PSYCHOLOGICAL TESTING AND RESEARCH SERVICES","Pasig City"  ],
                          ["PTS LPG OUTLET",""  ],
                          ["PUREGOLD DUTY FREE SUBIC, INC.",""  ],
                          ["PUREGOLD PRICE CLUB, INC.","Brgy. Camilmil, Calapan City, Oriental Mindoro"  ],
                          ["QUIMAN TRADING","Purok 10 Sta. Lucia, City of San Fernando Pampanga"  ],
                          ["R & SOL RTW & STORE",""  ],
                          ["R CT CAR2 AUTO SHOP",""  ],
                          ["R CT CAR2 AUTO SHOP",""  ],
                          ["R CT CAR2 AUTO SHOP",""  ],
                          ["R IGNACIO HARDWARE & CONSTRUCTION SUPPLY","40 18th St., E.B.B., Olongapo City"  ],
                          ["R IGNACIO TRADING","157 Avocado St. Sta Rita, Olongapo City"  ],
                          ["R. OCAMPO GENERAL MERCHANDISE",""  ],
                          ["R.A.G. AUTO PARTS",""  ],
                          ["R.C.S. TRAVELLING PEDDLER",""  ],
                          ["R.C.S. TRAVELLING PEDDLER",""  ],
                          ["R.E.E.M VARIETY STORE","1190 Rizal Ave., East Tapinac, Olongapo City"  ],
                          ["RADIOTEC COMMUNICATIONS INCORPORATED","553 Florentino Torres, Sta Cruz, Manila"  ],
                          ["RADIOTECH COMMUNICATION, INC.","2/F China Plaza Bldg., 1036-1038 Ongpin St., Sta Cruz Manila"  ],
                          ["RALI'S GRILL AND BAR",""  ],
                          ["RAM SAM GEN. MERCHANDISE",""  ],
                          ["RAMON ROSEMARIE ELECTRICAL SHOP & SUPPLY","7-26th St., E.B.B., Olongapo City"  ],
                          ["RANZ ALL WEATHER LAUNDRY SERVICES",""  ],
                          ["RANZ ALL WEATHER LAUNDRY SERVICES",""  ],
                          ["RAPID and PRECISE DIAGNOSTIC AND MEDICAL SUPPLIES","Sto. Cristo, Angeles City"  ],
                          ["RAYVEN'S FLOWERS",""  ],
                          ["RB AUTO WORKS","58-11th St., WestTapinac, Olongapo City"  ],
                          ["RBGM MEDICAL ENTERPRISES",""  ],
                          ["RCT CAR2 AUTO SHOP",""  ],
                          ["RCTF TRADING",""  ],
                          ["RDF MEATSHOP INC.",""  ],
                          ["READY FORM INC.","37 Balagtas St., cor. Apitong St., Marikina Heights, Marikina City"  ],
                          ["REAL ESTATE LESSOR",""  ],
                          ["RED RIBBON BAKESHOP OLONGAPO BRANCH",""  ],
                          ["RENATO S. RIBOT","18-C Herbosa Street, Tondo Manila"  ],
                          ["RENE's LOCKSMITH & RUBBER",""  ],
                          ["RENE'S LOCKSMITH & RUBBER STAMP",""  ],
                          ["REYES BARBECUE",""  ],
                          ["RG TROPHY RONEENA INC.","Caloocan City"  ],
                          ["RICH MIX LIGHTS & SOUNDS",""  ],
                          ["RICOS FASTFOOD & RESTAURANT",""  ],
                          ["RICOS FOOD VENTURES II",""  ],
                          ["RIZMER AUTO SUPPLY","Rizal Ave., E.B.B, Olongapo City"  ],
                          ["ROD & SOL RTW",""  ],
                          ["ROGERS ELECTRICAL AIRCON SERVICES & SUPPLY",""  ],
                          ["ROGER'S ELECTRICAL AIRCON SERVICES& SUPPLY",""  ],
                          ["ROLLY & CYNTHIA HOUSE OF","Pag-asa, Olongapo City"  ],
                          ["ROLLY &CYNTHIA HOUSE & CURTAINS",""  ],
                          ["RONA'S EDUCATIONAL SUPPLY",""  ],
                          ["RONA'S EDUCATIONAL SUPPLY",""  ],
                          ["RONEENA INCORPORATED",""  ],
                          ["RONNETTE'S EDUCATIONAL SUPPLY",""  ],
                          ["RONS FURNITURE INNOVATOR",""  ],
                          ["ROSARIO CABRIOUS-PROPIETOR TABITHA FOOD SHOP",""  ],
                          ["ROXAS LOCKSMITH",""  ],
                          ["ROYAL DUTY FREE SHOP",""  ],
                          ["ROYCE MOTOR CENTER INC.",""  ],
                          ["RPR CONSTRUCTION & GENERAL SERVICES",""  ],
                          ["RRL MARIKINA MARKETING CENTER INC.",""  ],
                          ["RTD AIR CONDITIONING SERVICES",""  ],
                          ["RUEL SAN DIEGO DRESS & TAILORING SHOP",""  ],
                          ["RVJ TRAVEL TOUR & SERVICES","4 Purok 2 San Pedro, Hagonoy Bulacan"  ],
                          ["S & R FOOD SERVICE",""  ],
                          ["S & S  MARKETING BRANCH 1",""  ],
                          ["SACHI SUBIC, INC.","SBFZ"  ],
                          ["SAFETYMATE INDUSTRIAL PRODUCTS",""  ],
                          ["SAFEWASTE INCORPORATED","9801 A-B-C Mabalacat Techno Center, Paralayunan Mabalacat Pampanga"  ],
                          ["SAFEWASTE MARKETING","Timog Park Angeles"  ],
                          ["SAFEWASTE MARKETING","Mabalacat, Pampanga"  ],
                          ["SAINT FRANCIS GARDEN CENTER T","1150 Rizal Ave., East Tapinac, Olongapo City"  ],
                          ["SAINT FX MULTI-MEDIA STUDIO",""  ],
                          ["SAKURA RESTAURANT",""  ],
                          ["SALLES STEEL FABRICATION & BUILDERS","57-18th St., E.B.B., Olongapo City"  ],
                          ["SAMERBY TRADING",""  ],
                          ["SAMERBY TRADING","12-A-26th St., E.B.B., Olongapo City"  ],
                          ["SAMMY TRADING & GENERAL SERVICES","Damsite, Lower Sibul, Natl Highway, W.B.B., Olongapo City "  ],
                          ["SAMMY'S TRADING & GEN. SERVICES",""  ],
                          ["SAM'S PIZZA",""  ],
                          ["SAN DIEGO TAILORING SHOP",""  ],
                          ["SAN FERNANDO ELEMENTARY SCHOOL TEACHERS M.P.C.","B.Mendoza St., Sto Rosario, City of San Fernando, Pampanga"  ],
                          ["SANBER AUTO PARTS",""  ],
                          ["SANCAPA VARIETY STORE",""  ],
                          ["SANCAPA VARIETY STORE",""  ],
                          ["SANLIE T-SHIRTS GARMENTS","90 Otero, Ave., Mabayuan, Olongapo City"  ],
                          ["SANNOVEX PHARMACEUTICAL","3F Josemar Bldg. Mandaluyng City"  ],
                          ["SANTOL COMPUTER WORLD PLUS",""  ],
                          ["SANVEN MEDICAL ENTERPRISES","City of San Fernando Pampanga"  ],
                          ["SARI SARI STORE",""  ],
                          ["SARMIENTO PEST CONTROL SERVICES","Iba Zambales"  ],
                          ["SAVER'S DIGITAL HUB APPLIANCE DEPOT",""  ],
                          ["SAVIOR MEDEVICES INC.","2F Global Enterprises Bldg., H.V. Dela Costa Salcedo VLG Makati City"  ],
                          ["SAVIOUR MEDEVICES, INC.","2nd Fl. Global Enterprise Bldg. H.V. Dela Costa St., Salgado Village, Makati City"  ],
                          ["SBWVMPCI",""  ],
                          ["SC FOOD CORPORATION",""  ],
                          ["SCANDINASIA VIKINGS CORPORATION",""  ],
                          ["SCENTDLE ENTERPRISE",""  ],
                          ["SCHOOLMART EDUCATION SUPPLY & GEN. MDSE.",""  ],
                          ["SEA MARINE SUBIC WORTHY SERVICES & TRADING CORP.","Bldg 8162 Lot2 Boton Area, SBFZ"  ],
                          ["SEAFOOD BY THE BAY",""  ],
                          ["SEE LAI TRADING",""  ],
                          ["SEE-LAI TRADING","115 Kessing St., New Kalalake, Olongapo City"  ],
                          ["SENSORMEDICS ENTERPRISES","Meycauayan, Bulacan"  ],
                          ["SERVANT ARTS & SIGNS",""  ],
                          ["SFP VILLA ALFREDO'S RESORT CORPORATION","Purok 1 Baliti, City of San Fernando, Pampanga"  ],
                          ["SGS PHILIPPINES, INC.",""  ],
                          ["SHAKEYS PIZZA RESTAURANT",""  ],
                          ["SHAN GENERAL MERCHANDISE","2704 Rizal Ave., E.B.B., Olongapo City"  ],
                          ["SHENG CHI DRUGSTORE",""  ],
                          ["SHOP & CARRY EXPRESSMART","32 Barretto St., E.B.B., Olongapo City"  ],
                          ["SILANGAN CANVAS & UPHOLSTERY",""  ],
                          ["SILVER SKY ENTERPRISES","Quezon City Manila"  ],
                          ["SIZZLING PLATE",""  ],
                          ["SJ ART WORK & SIGN",""  ],
                          ["SJC VAN & CAR FOR RENT","443 Mercurio Ext., Mabayuan, Olongapo City"  ],
                          ["SM APPLIANCE CENTER ","SM City Olongapo "  ],
                          ["SM DEPARTMENT STORE OLONGAPO",""  ],
                          ["SM DEPARTMENT STORE OLONGAPO",""  ],
                          ["SM SUPERMARKET-OLONGAPO",""  ],
                          ["SMARTGUARD PHILIPPINES","Bacolod City"  ],
                          ["SMARTGUARD PHILIPPINES, INC.","Block 4, Lot 5 & 6 7th St., Capitol Subd., Brgy 7, Bacolod City"  ],
                          ["SOL RTW VARIETY STORE",""  ],
                          ["SOLAR FLEX MARKETING",""  ],
                          ["SOLAR ICE ENTERPRISES","Blk. 5 Lot 64 Sunrays Village, Guyong, Sta. Maria, Bulacan"  ],
                          ["SOLAR LED STREET LIGHTING SYSTEM",""  ],
                          ["SOLID METAL ENGRAVING SHOP",""  ],
                          ["SON'S WEN FASTFOOD",""  ],
                          ["SON'S WEN FASTFOOD",""  ],
                          ["SOPIMUS PRINTNET SOLUTIONS","West Tapinac, Olongapo City"  ],
                          ["SPARE AUTO SUPPLY",""  ],
                          ["SPEED LANE TRANSPORT & SERVICES",""  ],
                          ["SPEED PRINT GRAPHICS","655 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["SPEEDPRINT GRAPHICS",""  ],
                          ["SPEEDPRINT GRAPHICS",""  ],
                          ["SRM AUTO REPAIR SHOP",""  ],
                          ["ST FRANCIS GARDEN CENTER","6 Caron St., W.B.B., Olongapo City"  ],
                          ["STA ANA ENTERPRISES",""  ],
                          ["STA MONICA GLASS & ALUMINUM",""  ],
                          ["STA RITA VULCANIZING",""  ],
                          ["STA. RITA FILTRATION GATE OPERATORS & DRIVERS ASSOCIATION OF OLONGAPO CITY (YELLOW JEEP) INC.",""  ],
                          ["STANDARD BLUE AURO SUPPLY",""  ],
                          ["STARBUCKS COFFEE",""  ],
                          ["SUBIC ADS ",""  ],
                          ["SUBIC AMUSEMENT ENTERPRISES INC.",""  ],
                          ["SUBIC AUTO RESTORATION & GEN. MDSE.",""  ],
                          ["SUBIC BAY EXPLORATORIUM, INC.",""  ],
                          ["SUBIC BAY SILK SCREEN PRINTING",""  ],
                          ["SUBIC BAY TRAVELERS HOTEL & EVENT CENTER INC.",""  ],
                          ["SUBIC BAY VAN TRANSPORT DRIVERS & OPRTS ASSOC INC.",""  ],
                          ["SUBIC BAY VENEZIA HOTEL & RESTAURANT",""  ],
                          ["SUBIC BAY VENEZIZ HOTEL",""  ],
                          ["SUBIC BAY YATCH CLUB",""  ],
                          ["SUBIC BISTRO AMERICANO CORP.",""  ],
                          ["SUBIC CAWAG UPLAND FARMER'S ASS'N (SCUFA), INC.",""  ],
                          ["SUBIC COASTAL DEV. CORP.",""  ],
                          ["SUBIC DUTY FREE SHOP, INC.",""  ],
                          ["SUBIC FORTUNE HONGKONG SEAFOOD RESTAURANT",""  ],
                          ["SUBIC HOMES INC.",""  ],
                          ["SUBIC INTERNATIONAL HOTEL CORP.",""  ],
                          ["SUBIC KOREAN HOTEL & RESTAURANT & GEN. MDSE. INC.","SBFZ"  ],
                          ["SUBIC LIGHTHOUSE CONST. & DEV'T CORP.","40 National Hi-way, Barretto, Olongapo City"  ],
                          ["SUBIC RESIDENCIA'S",""  ],
                          ["SUBICWATER & SEWERAGE CO., INC.",""  ],
                          ["SUBIK AIR SALES & GENERAL SERVICES",""  ],
                          ["SUNLIGHT GLASS & ALUMINUM SUPPLY",""  ],
                          ["SUNNY SMILE FOOD CORP.",""  ],
                          ["SWEET TOOTH CORP.(GOLDILOCKS)",""  ],
                          ["SXY GENERAL MERCHANDISE",""  ],
                          ["SYNERGY SALES INT'L CORP.",""  ],
                          ["T.H.E. ELECTRONICS BOUTIQUE INC. GENERAL MERCHANDISE","Harbor Point, SBFZ"  ],
                          ["TACTICAL OPTION GENERAL MERCHANDISE","Para�aque City"  ],
                          ["TAIJIMAN INTERNATIONAL VENTURES","62A Innovative St. Subic Bay Gateway Park, SBFZ"  ],
                          ["TAMAYO'S TRADING & MACHINE SHOP",""  ],
                          ["TAMPENGCO CONSTRUCTION & SUPPLIES",""  ],
                          ["TANAWIN BED & BREAKFAST","Tala Orani, Bataan"  ],
                          ["TAUTON WELDING SHOP",""  ],
                          ["TEARDROPS PURIFIED DRINKING WATER",""  ],
                          ["TELETRONICS COMPUTERS & ELECTRONICS","16 Mt. Apo St., East Tapinac, Olongapo City"  ],
                          ["TEMPURA JAPANESE GRILL",""  ],
                          ["TERIYAKI BOY",""  ],
                          ["TESTON MARKETING",""  ],
                          ["TEXAS JOE'S HOUSE OF RIBS AND TJ'S SALOON",""  ],
                          ["THABBY'S CATERING SERVICES",""  ],
                          ["THAN-THAN'S FARM RESORT","Sta. Monica, Lubao, Pampanga"  ],
                          ["THE DIY SHOP CORP.",""  ],
                          ["THE LIGHTHOUSE MARINA RESORT",""  ],
                          ["THE UNIFIED IT DISTRIBUTION-OLONGAPO INC.",""  ],
                          ["THREE J'S HARDWARE & CONSTRUCTION SUPPLY","Afable St., E.B.B., Olongapo City"  ],
                          ["TINEE WATER REFILLING STATION","Benedictine Nuns, salong, Calapan City Mindoro"  ],
                          ["TINIO'S DRYGOODS",""  ],
                          ["TIVAS HOMEMADE PRODUCT",""  ],
                          ["TIXSPS FEATURES ENTERPRISES","1840 Rizal Ave., EBB, Olongapo City"  ],
                          ["TOLENTINO UPHOLSTERY SHOP",""  ],
                          ["TOMIE'S MOTOR WORKS","Mc Arthur Hi-way, San Isidro, City of San Fernando Pampanga"  ],
                          ["TOMIE'S MOTOR WORKS","Mc arthur Hi-way, San Isidro, City of San Fernando Pampanga"  ],
                          ["TONY AND ANN'S CATERING SERVICES",""  ],
                          ["TOP COMS MARKETING","1647 Taft Ave., Malate Manila"  ],
                          ["TORING'S DRY GOODS",""  ],
                          ["TOWER MEDICAL","#12 Mahiyain St., Sikatuna Village, Quezon City"  ],
                          ["TOYOTA BALINTAWAK",""  ],
                          ["TOYOTA SAN FERNANDO PAMPANGA INC.",""  ],
                          ["TOYOTA SAN FERNANDO PAMPANGA INC.",""  ],
                          ["TRAVEL LODGE",""  ],
                          ["TRI STAR RENT-A-CAR",""  ],
                          ["TRIANGLE ACE LUMBER & HARDWARE","39-21st St., W.B.B., Olongapo City"  ],
                          ["TRIANGLE ACE LUMBER & HARDWARE",""  ],
                          ["TRICKSHOT BADMINTON COURT",""  ],
                          ["TRIPLE W. CYCLE & LUBE PARTS",""  ],
                          ["TROPICAL BAY RESTAURANT & CATERING",""  ],
                          ["TTNJ GENERAL MERCHANDISE","Sitio Matang EB, Hi-way, Hanjin, Cawag, Subic, Zambales"  ],
                          ["TUMMYTUMS FOODS CORPORATION",""  ],
                          ["TUV RHEINLAND PHILIPPINES","Makati City"  ],
                          ["TUV RHEINLAND PHILIPPINES INC.",""  ],
                          ["TVD ADVERTISING","1 Harris St., E.B.B., Olongapo City"  ],
                          ["TVD ADVERTISING","1 Harris, E.B.B., Olongapo City"  ],
                          ["TWIN LLKITCHENETTE",""  ],
                          ["U-BIX SUBIC BAY CORPORATION",""  ],
                          ["ULANDAY FLOWER SHOP",""  ],
                          ["ULO NG APO VISION ELECTRONICS & GEN. MDSE.",""  ],
                          ["ULTRA KIT GENERAL MERCHANDISE",""  ],
                          ["UNITECH INDUSTRIAL SALES INC.",""  ],
                          ["UNITED DIAGNOSTIC SUPPLY","Unit C LRDC Annex Bldg #141 A Sgt. Esguerra Ave.,Quezon City"  ],
                          ["UNITED LABORATORIES INC.","66 United St., Mandaluyong City"  ],
                          ["UNIVERSAL CAR RENTAL",""  ],
                          ["UNIVERSAL MAGAZINE EXCHANGE CORP.",""  ],
                          ["uniZENTRO APPLIANCE & FURNITURE STORE",""  ],
                          ["USA PENTAGRAPH ADVERTISING",""  ],
                          ["V�B BUILDERS","84 Calapandayan, Subic Zambales"  ],
                          ["V8 DESIGN STUDIO","50  Gordon Ave., Olongapo city"  ],
                          ["VALENZUELA MOTOR SHOP",""  ],
                          ["VALLERY ENTERPRISES","City of San Fernando Pampanga"  ],
                          ["VANILLA ICE PEARL",""  ],
                          ["VANS BONG STORE",""  ],
                          ["VASCO'S HOTEL & RESTAURANT",""  ],
                          ["VELUE TRANS",""  ],
                          ["VERCON'S SUPERMARKET & DEPARTMENT STORE","23 Arthur, W.B.B., Olongapo City"  ],
                          ["VIADOMA ENTERPRISES",""  ],
                          ["VICARISH PUBLICATION AND TRADING INC.",""  ],
                          ["VICTORIA TRADING","8 Afable St., E.B.B., Olongapo City"  ],
                          ["VICTORY LINER INC.",""  ],
                          ["VILLA CARMEN RESORT, HOTEL & RESTAURANT",""  ],
                          ["VIRGILIO GONZALES MUSICAL INSTRUMENT REPAIR SHOP & DEALER OF KINDS OF INSTRUMENT",""  ],
                          ["VISTA RENT A CAR",""  ],
                          ["VIZON ENTERPRISES","B12-L3-P3, Dizon Estate, San Agustin, San Fernando City Pampanga"  ],
                          ["VME ENVIRONMENT SERVICES","Sinabacan Candelaria Zambales 2212"  ],
                          ["WAF BROS. TECHNOLOGIES PHILS. INC.","Gilmore ave., New Manila, Quezon City"  ],
                          ["WALLGREEN INDUSTRIAL VENTURES CORP.",""  ],
                          ["WALLGREEN INDUSTRIAL VENTURES CORP.",""  ],
                          ["WATERCRAFT VENTURE, CORPORATION","SBFZ"  ],
                          ["WBT GEN. MERCHANDISE",""  ],
                          ["WBT GEN. MERCHANDIZE","1295 Rizal Ave., West Tapinac, Olongapo City"  ],
                          ["WE CARE DRUG-OLONGAPO BRANCH",""  ],
                          ["WE CARE DRUG-OLONGAPO BRANCH II",""  ],
                          ["WELLCOM TELECOM SUPERMARKET INC.",""  ],
                          ["WHITEROCK WATERPARK & BEACH RESORT",""  ],
                          ["WILD ORCHID BEACH RESORT",""  ],
                          ["WILJOY PHOTO SHOP",""  ],
                          ["WILLIS  RESTAURANT",""  ],
                          ["WILMA'S EATERY CORNER",""  ],
                          ["WIMPY'S BURGER & ICE CREAM PARLOR",""  ],
                          ["WINDSHEAR INT'L. PHIL., INC.","6-B C.C. Benitez St., Cubao, Quezon City"  ],
                          ["WM ENTERPRISES","Brgy. Bugnay Diadi Nueva Vizcaya"  ],
                          ["WORTHY BROTHER PHARMA, INC.","San Juan, Castillejos, zambales"  ],
                          ["XAVE-NET DRY GOODS",""  ],
                          ["XEROGRAFIX BUSINESS PRODUCTS & SERVICES, INC.",""  ],
                          ["XTREMELY XPRESSO CAF�",""  ],
                          ["XYLIDINE ENTERPRISES",""  ],
                          ["YAMANARI AUTO SUPPLY",""  ],
                          ["YBC SUPERMARKET",""  ],
                          ["YELLOW CAB PIZZA",""  ],
                          ["YOKOHAMA PRECISION TEK MOTOR SERV. CORP.",""  ],
                          ["YOLLY'S VARIETY STORE",""  ],
                          ["YUAN JAPANESE FOODS","SBFZ"  ],
                          ["ZAFIRE DISTRIBUTORS, INC.","Timog Subd., Angeles City"  ],
                          ["ZAMBALES HARDWARE","E-21st St., E.B.B., Olongapo City"  ],
                          ["ZAMBALES HERALD",""  ],
                          ["ZAMBALES SOLID CONSTRUCTION SUPPLY","14-21st ST., E.B.B., Olongapo City"  ],
                          ["ZAMBALES SOLID CONSTRUCTION SUPPLY",""  ],
                          ["ZAMODCA TRANSPORT SERVICE COOP., INC.",""  ],
                          ["ZAMODCA TRANSPORT SERVICE COOP., INC.",""  ],
                          ["ZENAIDA R. JAVIER COINS & COMMEMORATIVE ITEMS",""  ],
                          ["ZENCO FOOTSTEP",""  ],
                          ["ZEP RENT A CAR",""  ],
                          ["ZILD ENTERPRISES",""  ],
                          ["ZSARIZ'S ENTERPRISES",""  ],
                          ["ZUELLIG PHARMA CORP.","Cabuyao, Laguna"  ],
                          ["L & L TROPIACAL BAY RESTAURANT",""  ],
                          ["NAD A.R.A GENERAL MERCHANDISE","40 Elica�o St., E.B.B., Olongapo City"  ],
                          ["LUCKY DALE SUBIC INTERNATIONAL INC.","SBFZ"  ],
                          ["SUZUKI AUTO PAMPANGA",""  ],
                          ["INDUSTRIAL & TRANSPORT EQUIPMENT, INC. PAMPANGA",""  ],
                          ["WIMPY'S FOOD PLAZA NO. 2",""  ],
                          ["CRONEWOOD, INC.",""  ],
                          ["JOLLIBEE",""  ],
                          ["BALIWAG LECHON MANOK INC.",""  ],
                          ["RAINBOW LAND HOTEL",""  ],
                          ["SUBIC BERRINGER HOTELS AND RESORTS INC.",""  ],
                          ["SUBIC BAY WORKERS/VOLUNTEERS MULTI-PURPOSE COOPERATIVE",""  ],
                          ["BARTLE BEYL, INC.",""  ],
                          ["GUANZON MERCHANDISING CORPORATION","2725 Rizal Ave., W.B.B., Olongapo City"  ]
                        ];
    public function run()
    {
    	$this->supplier_type();
        $this->supplier_info();
    }

    public function supplier_type(){
    	 $faker = Faker\Factory::create();
        $type = array('Service Business','Merchandising Business','Manufacturing  Business');
        for ($i = 0; $i < count($type); $i++) {
        	$type_rnd = array_rand($type,1);
            DB::table('supplier_type')->insert([ //,
                'desc' => $type[$i],
            ]);
        }

    }

    public function supplier_info(){
         $suppliers = $this->suppliers;

        $limit = 100;
        $type = array(1,2,3);


        for ($x = 0; $x < count($suppliers); $x++) {
        	$type_rnd = array_rand($type,1);
            $cmpny = DB::table('supplier_info')->insertGetId([ //,
                'title' => $suppliers[$x][0],
                'desc' => $suppliers[$x][0],
                'type' => $type[$type_rnd],
            ]);

            if($suppliers[$x][1]!=''){
                DB::table('supplier_address')->insert([ //,
                'details' => $suppliers[$x][1],
                'supplier_id' => $cmpny
            ]);
            }
        }
    }
}
